ci_service: travis_ci
coverage_service: coveralls
xcodeproj: OptimizelySDKiOS/OptimizelySDKiOS.xcodeproj
workspace: OptimizelySDK.xcworkspace
scheme: OptimizelySDKiOS
input_format: profdata
build_directory: ./
source_directory: Pods
