# Uncomment this line to define a global platform for your project
  platform :ios, '9.0'

target 'OptimizelySDKShared' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

  # Pods for OptimizelySDKShared
    pod 'JSONModel', '1.3.0'

  target 'OptimizelySDKSharedTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OHHTTPStubs'
    pod 'OCMock'
  end

end
