project 'OptimizelySDKCore.xcodeproj/'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
  
def common_pods
  pod 'JSONModel', '1.3.0'
end

def common_test_pods
  pod 'OHHTTPStubs'
  pod 'OCMock'
end
 
use_frameworks!

target 'OptimizelySDKCoreiOS' do
  platform :ios, '10.1'
  common_pods
end
 
target 'OptimizelySDKCoreTVOS' do
  platform :tvos, '10.0'
  common_pods
end

target 'OptimizelySDKCoreiOSTests' do
  common_pods
  common_test_pods
end

target 'OptimizelySDKCoreTVOSTests' do
  common_pods
  common_test_pods
end
