# Uncomment this line to define a global platform for your project
platform :tvos, '9.0'

target 'OptimizelySDKTVOS' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for OptimizelySDKTVOS
  pod 'JSONModel', '1.3.0'

  target 'OptimizelySDKTVOSTests' do
    inherit! :search_paths
    # Pods for testingi
    pod 'OHHTTPStubs'
    pod 'OCMock'
  end

end
